# GitHub Actions workflow for Amplify preview deployments
# This workflow runs on pull requests to provide preview deployments

name: Amplify Preview Deployment

on:
  pull_request:
    branches: [main, staging]
    types: [opened, synchronize, reopened]

jobs:
  preview-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate environment
        run: npm run env:validate
        env:
          NODE_ENV: production
          NEXT_PUBLIC_SITE_NAME: "Preview Site"

      - name: Validate content structure
        run: npm run content:validate-structure

      - name: Validate content
        run: npm run content:validate

      - name: Type check
        run: npm run type-check

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1

      - name: Comment PR with preview info
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployment will be available once merged to a preview branch in Amplify Console.'
            })
