name: Quality Check

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Use Node 22.19.0 to satisfy vite@7 & lighthouse@13
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Print Node & NPM versions (debug)
        run: |
          node -v
          npm -v
          echo "Node engine requirement: >=22.19.0"
          echo "NPM engine requirement: >=10.8.0"

      # ⚙️ Use npm ci for reproducible builds
      - name: Clean install dependencies
        run: npm ci

      # ✅ Ensure the lockfile hasn't changed (catches local npm install drift)
      - name: Verify lockfile consistency
        run: |
          echo "Checking lockfile consistency..."
          git diff --exit-code --quiet package-lock.json || (
            echo "❌ package-lock.json has been modified during npm ci"
            echo "This indicates lockfile inconsistency between local and CI environments"
            echo "Please run 'npm ci' locally and commit any changes to package-lock.json"
            exit 1
          )

      # 🧠 Type checking (conditional execution)
      - name: Type check
        run: |
          if npm run type-check --if-present; then
            echo "✅ Type checking passed"
          else
            echo "⚠️ Type checking not available or failed"
          fi
        continue-on-error: false

      # 🧹 Linting (conditional execution)
      - name: Lint code
        run: |
          if npm run lint --if-present; then
            echo "✅ Linting passed"
          else
            echo "⚠️ Linting not available or failed"
          fi
        continue-on-error: false

      # 🧪 Unit tests (conditional execution)
      - name: Run unit tests
        run: |
          if npm test --if-present; then
            echo "✅ Unit tests passed"
          else
            echo "⚠️ Unit tests not available or failed"
          fi
        continue-on-error: false

      # 🏗️ Build Next.js project with comprehensive environment setup
      - name: Build project
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production
        run: |
          echo "🏗️ Building project with Node.js $(node -v)"
          npm run build
          echo "✅ Build completed successfully"

      # 🧾 Verify build artifacts and key assets
      - name: Verify build output and assets
        run: |
          echo "🔍 Verifying build output..."
          
          # Check if build directory exists
          if [ -d ".next" ]; then
            echo "✅ .next build directory exists"
          else
            echo "❌ .next build directory not found"
            exit 1
          fi
          
          # Check key public assets
          if [ -f "public/images/hero/aston-martin-db6-website.webp" ]; then
            echo "✅ Hero image exists"
          else
            echo "❌ Missing hero image: public/images/hero/aston-martin-db6-website.webp"
            exit 1
          fi
          
          # Check if package.json has correct engines
          if grep -q '"node": ">=22.19.0"' package.json; then
            echo "✅ Node.js engine requirement is correctly set"
          else
            echo "⚠️ Node.js engine requirement may need updating in package.json"
          fi
          
          echo "✅ All verifications passed"